server:
  port: 8080

spring:
  application:
    name: oracle-tarot-service
  profiles:
    active: dev # Mặc định kích hoạt profile dev khi chạy local

# Swagger OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html