server:
  port: 8080

spring:
  application:
    name: oracle-tarot-service
  profiles:
    active: dev

# Cấu hình Bảo mật JWT
application:
  security:
    jwt:
      secret-key: oracle-tarot-super-secret-key-256-bits-minimum-required-for-hmac-sha-algorithm-security
      expiration-ms: 604800000

# Swagger OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html